# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
pod 'BadgeSwift'
end

target 'ExampleSwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleSwiftUI

end

target 'Parchment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Parchment

  target 'ParchmentTests' do
    # Pods for testing
  end

  target 'ParchmentUITests' do
    # Pods for testing
  end

end
